---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-openshift-machine-config-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-machine-config-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Role for accessing metrics exposed by MCD in MCO namepsace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-machine-config-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
---
# Grant cluster-monitoring access to MCD metrics in MCO namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-machine-config-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
