apiVersion: v1
kind: Namespace
metadata:
  name: openshift-machine-config-operator
  annotations:
    openshift.io/node-selector: ""
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    name: openshift-machine-config-operator
    openshift.io/run-level: "1"
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-openstack-infra
  annotations:
    openshift.io/node-selector: ""
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    name: openshift-openstack-infra
    openshift.io/run-level: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kni-infra
  annotations:
    openshift.io/node-selector: ""
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    name: openshift-kni-infra
    openshift.io/run-level: "1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-ovirt-infra
  annotations:
    openshift.io/node-selector: ""
    exclude.release.openshift.io/internal-openshift-hosted: "true"
  labels:
    name: openshift-ovirt-infra
    openshift.io/run-level: "1"
